### ISSUE TITLE
What about migrations?

### ISSUE THREAD

**Issue by snipiba** [LukeTowers/oc-laravelpackagesexample-plugin#3]
When package contains some migrations that need to be run, there must be some kind of check, then, probably, copying migration files inside plugin and mentoined it in version.yaml or something, right?

**Comment by LukeTowers** [comment]
@snipiba exactly, see https://wintercms.com/docs/help/using-composer#laravel-migrations-models

**Comment by snipiba** [comment]
> @snipiba exactly, see https://wintercms.com/docs/help/using-composer#laravel-migrations-models

![image](https://github.com/LukeTowers/oc-laravelpackagesexample-plugin/assets/3245533/5fb9b165-f313-4fb3-9b98-a3d09d191d7c)
what exactly?

**Comment by LukeTowers** [comment]
Looks like I missed setting up the redirect on that URL, added it now and here's the updated link: https://wintercms.com/docs/v1.2/docs/architecture/using-composer#migrations--models

**Comment by snipiba** [comment]
> contains some migrations that need to be run, there must be some kind of check, then, probably, copying migration files inside plugin and mentoined it in version.ya

ok, im lil bit confused, because we talking about OC plugin and followed by wintercms, etc. i know history about oc and winter, and probably it will work on both. just currious.
